# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       plasma-nm

# >> macros
# << macros

Summary:    Plasma Next applet written in QML for managing network connections
Version:    5.0.0
Release:    1
Group:      System/Base
License:    LGPLv2+ and GPLv2+
URL:        http://www.kde.org
Source0:    %{name}-%{version}.tar.xz
Source100:  plasma-nm.yaml
Source101:  plasma-nm-rpmlintrc
Requires:   kf5-filesystem
Requires:   NetworkManager >= 0.9.8
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Xml)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  pkgconfig(Qt5Concurrent)
BuildRequires:  pkgconfig(Qt5Test)
BuildRequires:  pkgconfig(Qt5PrintSupport)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(NetworkManager) >= 0.9.8
BuildRequires:  pkgconfig(ModemManager) >= 1.0.0
BuildRequires:  kf5-rpm-macros
BuildRequires:  extra-cmake-modules
BuildRequires:  qt5-tools
BuildRequires:  ki18n-devel
BuildRequires:  kwindowsystem-devel
BuildRequires:  kservice-devel
BuildRequires:  kcompletion-devel
BuildRequires:  kwidgetsaddons-devel
BuildRequires:  kio-devel
BuildRequires:  kcoreaddons-devel
BuildRequires:  kwallet-devel
BuildRequires:  kitemviews-devel
BuildRequires:  kxmlgui-devel
BuildRequires:  kconfigwidgets-devel
BuildRequires:  kiconthemes-devel
BuildRequires:  solid-devel
BuildRequires:  kdbusaddons-devel
BuildRequires:  knotifications-devel
BuildRequires:  plasma-devel
BuildRequires:  kdeclarative-devel
BuildRequires:  kinit-devel
BuildRequires:  kdelibs4support-devel
BuildRequires:  libmm-qt-devel
BuildRequires:  libnm-qt-devel

%description
Plasma Next applet written in QML for managing network connections


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
%kf5_make
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
%kf5_make_install
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_prefix}/*
# >> files
# << files
